/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package viewforExpenses;


import com.itextpdf.text.Document;
import java.util.logging.Level;
import java.util.logging.Logger;


import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;
import javax.swing.table.DefaultTableModel;
import service.ExpenseInterface;
import service.UserInterface;
import model.Expense;
import model.User;

import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;

import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import java.text.DateFormat;
import java.text.ParseException;
import java.util.Arrays;
import java.util.Calendar;
import model.Expense;
import model.User;
import service.ExpenseInterface;


/**
 *
 * @author hp
 */
public class Dashboard extends javax.swing.JFrame {
    private User currentUser;
    private Long selectedExpenseId;
    private boolean isAdmin;
    private ExpenseInterface expenseService;
    private UserInterface userService;


    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
       
   }
    public Dashboard(User user) {
        initComponents();
        initializeServices();
        this.currentUser = user;
        Display();
    }
    
    
    public Dashboard(User user, boolean isAdmin) {
        this.currentUser = user;
        this.isAdmin = isAdmin;
        initComponents();
        initializeServices();
       
        Display();
    }
        
    private void initializeServices() {
        try {
            Registry registry = LocateRegistry.getRegistry("127.0.0.1", 5000);
            expenseService = (ExpenseInterface) registry.lookup("expenses");
            userService = (UserInterface) registry.lookup("users");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error connecting to server: " + ex.getMessage(), "Server Error", JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabsCategory = new javax.swing.JTabbedPane();
        jPanelExpenses = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        ExpenseAmountTxt = new javax.swing.JTextField();
        ExpenseAddBtn = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        ExpenseDescriptionTxt = new javax.swing.JTextField();
        expenseAddErrorLabel = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        DisplayExpenseBtn1 = new javax.swing.JButton();
        SavePdfBtn = new javax.swing.JButton();
        updateExpenseBtn = new javax.swing.JButton();
        jDateChooserExpenseDate1 = new com.toedter.calendar.JDateChooser();
        DeleteExpenseBtn = new javax.swing.JButton();
        ExitBtn = new javax.swing.JButton();
        jScrollPane1Expense = new javax.swing.JScrollPane();
        jTableExpense = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        avg = new javax.swing.JTextField();
        total = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        expenseAddErrorLabel1 = new javax.swing.JLabel();
        DisplayExpenseBtn2 = new javax.swing.JButton();
        searchExpenses = new javax.swing.JButton();
        jDateChooserExpenseDate2 = new com.toedter.calendar.JDateChooser();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableExpense1 = new javax.swing.JTable();
        jPanelProfile = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jButtonUpdateProfile = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19UsernameError = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        FnameTxt = new javax.swing.JTextField();
        UsernameTxt = new javax.swing.JTextField();
        phoneNumberTxt = new javax.swing.JTextField();
        oldPasswordTxt = new javax.swing.JPasswordField();
        newPasswordTxt = new javax.swing.JPasswordField();
        updateProfileBtn = new javax.swing.JButton();
        jPanelProfile1 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jButtonUpdateProfile1 = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel19UsernameError1 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jTextField4Fname1 = new javax.swing.JTextField();
        jTextField4Username1 = new javax.swing.JTextField();
        jTextField4Fonenumber1 = new javax.swing.JTextField();
        jTextField4passold1 = new javax.swing.JPasswordField();
        jPasswordField1passwordnew1 = new javax.swing.JPasswordField();
        updateProfileBtn3 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabsCategory.setBackground(new java.awt.Color(0, 153, 153));
        tabsCategory.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tabsCategory.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tabsCategory.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tabsCategoryStateChanged(evt);
            }
        });
        tabsCategory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabsCategoryMouseClicked(evt);
            }
        });

        jPanelExpenses.setBackground(new java.awt.Color(204, 204, 255));
        jPanelExpenses.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelExpensesMouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel4.setText("Expense");

        jLabel8.setText("Enter Amount");

        jLabel9.setText("Select Category");

        jLabel10.setText("Date");

        ExpenseAmountTxt.setToolTipText("Enter Amount");

        ExpenseAddBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ExpenseAddBtn.setText("Save");
        ExpenseAddBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExpenseAddBtnActionPerformed(evt);
            }
        });

        jLabel11.setText("Description");

        ExpenseDescriptionTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExpenseDescriptionTxtActionPerformed(evt);
            }
        });

        expenseAddErrorLabel.setForeground(new java.awt.Color(255, 51, 51));
        expenseAddErrorLabel.setText("  ");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Essentials(food, groceries, utilities, and housing, schoolfees)", "Transportation(commuting, fuel, public transportation,vehicle maintenance)", "health wellness(healthcare, fitness memberships, medical expenses)", "Entertainment(leisure activities,dining out, movies, concerts, hobbies, vacations)", " ", " " }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        DisplayExpenseBtn1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        DisplayExpenseBtn1.setText("Display");
        DisplayExpenseBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisplayExpenseBtn1ActionPerformed(evt);
            }
        });

        SavePdfBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        SavePdfBtn.setText("Save Report as PDF");
        SavePdfBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SavePdfBtnActionPerformed(evt);
            }
        });

        updateExpenseBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        updateExpenseBtn.setText("Update");
        updateExpenseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateExpenseBtnActionPerformed(evt);
            }
        });

        DeleteExpenseBtn.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        DeleteExpenseBtn.setText("Delete");
        DeleteExpenseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteExpenseBtnActionPerformed(evt);
            }
        });

        ExitBtn.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        ExitBtn.setText("Exit");
        ExitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                System.exit(0);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(89, 89, 89)
                                .addComponent(jLabel9)
                                .addGap(191, 191, 191)
                                .addComponent(jLabel10)
                                .addGap(231, 231, 231))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(ExpenseAmountTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(1, 1, 1)
                                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jDateChooserExpenseDate1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(ExpenseDescriptionTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(jLabel11))))
                    .addComponent(expenseAddErrorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ExpenseAddBtn)
                    .addComponent(DisplayExpenseBtn1))
                .addGap(40, 40, 40)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(updateExpenseBtn)
                        .addGap(18, 18, 18)
                        .addComponent(DeleteExpenseBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ExitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(SavePdfBtn)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ExpenseAddBtn)
                                    .addComponent(updateExpenseBtn)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel9)))
                                    .addComponent(jLabel11))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jDateChooserExpenseDate1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(ExpenseAmountTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(ExpenseDescriptionTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(ExitBtn)
                                .addGap(5, 5, 5))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(DeleteExpenseBtn)
                                .addGap(18, 18, 18)))))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(expenseAddErrorLabel)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(DisplayExpenseBtn1)
                        .addComponent(SavePdfBtn)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane1Expense.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane1ExpenseMouseClicked(evt);
            }
        });

        jTableExpense.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Amount", "Category", "Date", "Description"
            }
        ));
        jTableExpense.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableExpenseMouseClicked(evt);
            }
        });
        jScrollPane1Expense.setViewportView(jTableExpense);

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));
        jPanel1.setForeground(new java.awt.Color(0, 51, 51));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Average expenses:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Total Expenses:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(avg, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(avg, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelExpensesLayout = new javax.swing.GroupLayout(jPanelExpenses);
        jPanelExpenses.setLayout(jPanelExpensesLayout);
        jPanelExpensesLayout.setHorizontalGroup(
            jPanelExpensesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelExpensesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(358, 358, 358))
            .addGroup(jPanelExpensesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelExpensesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 1489, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanelExpensesLayout.createSequentialGroup()
                .addComponent(jScrollPane1Expense)
                .addContainerGap())
        );
        jPanelExpensesLayout.setVerticalGroup(
            jPanelExpensesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelExpensesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1Expense, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tabsCategory.addTab("Record ", jPanelExpenses);

        jLabel20.setText("Date");

        expenseAddErrorLabel1.setForeground(new java.awt.Color(255, 51, 51));
        expenseAddErrorLabel1.setText("  ");

        DisplayExpenseBtn2.setText("Display");
        DisplayExpenseBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisplayExpenseBtn2ActionPerformed(evt);
            }
        });

        searchExpenses.setBackground(new java.awt.Color(0, 0, 0));
        searchExpenses.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        searchExpenses.setForeground(new java.awt.Color(255, 255, 255));
        searchExpenses.setText("Exit");
        searchExpenses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                System.exit(0);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jDateChooserExpenseDate2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(147, 147, 147)
                                .addComponent(DisplayExpenseBtn2))
                            .addComponent(jLabel20))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(searchExpenses))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(expenseAddErrorLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(DisplayExpenseBtn2)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jDateChooserExpenseDate2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(searchExpenses)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(expenseAddErrorLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane2MouseClicked(evt);
            }
        });

        jTableExpense1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Amount", "Category", "Date", "Description"
            }
        ));
        jScrollPane2.setViewportView(jTableExpense1);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1367, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(137, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(110, Short.MAX_VALUE))
        );

        tabsCategory.addTab("Search ", jPanel4);

        jPanelProfile.setBackground(new java.awt.Color(153, 153, 255));

        jLabel12.setText("Full Names :");

        jLabel16.setText("Old Password :");

        jButtonUpdateProfile.setText("Update");
        jButtonUpdateProfile.setEnabled(false);
        jButtonUpdateProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateProfileActionPerformed(evt);
            }
        });

        jLabel17.setText("Username");

        jLabel18.setText("New Password :");

        jLabel19UsernameError.setText(" ");

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Exit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel3.setText("Phone_number:");

        oldPasswordTxt.setEditable(false);

        updateProfileBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        updateProfileBtn.setText("Update");
        updateProfileBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateProfileBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(246, 246, 246)
                .addComponent(jButtonUpdateProfile)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 358, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(150, 150, 150))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(UsernameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(newPasswordTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel19UsernameError, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel18)
                    .addComponent(jLabel12)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(84, 84, 84)
                                .addComponent(jLabel13))
                            .addComponent(FnameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(92, 92, 92)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(phoneNumberTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(oldPasswordTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(updateProfileBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(399, 399, 399))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FnameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phoneNumberTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(UsernameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19UsernameError)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(oldPasswordTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(newPasswordTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(updateProfileBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(697, 697, 697)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonUpdateProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addGap(22, 22, 22))
        );

        jPanelProfile1.setBackground(new java.awt.Color(153, 153, 255));

        jLabel14.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel14.setText("Profile");

        jLabel15.setText("Full Names :");

        jLabel21.setText("Old Password :");

        jButtonUpdateProfile1.setText("Update");
        jButtonUpdateProfile.setEnabled(false);
        jButtonUpdateProfile1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateProfile1ActionPerformed(evt);
            }
        });

        jLabel22.setText("Username");

        jLabel23.setText("New Password :");

        jLabel19UsernameError1.setText(" ");

        jButton9.setBackground(new java.awt.Color(0, 0, 0));
        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setText("Exit");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                System.exit(0);
            }
        });

        jLabel5.setText("Phone_number:");

        jTextField4passold1.setEditable(false);

        updateProfileBtn3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        updateProfileBtn3.setText("Update");
        updateProfileBtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateProfileBtn3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(246, 246, 246)
                .addComponent(jButtonUpdateProfile1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 358, Short.MAX_VALUE)
                .addComponent(jButton9)
                .addGap(150, 150, 150))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22)
                    .addComponent(jTextField4Username1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPasswordField1passwordnew1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel19UsernameError1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel23)
                    .addComponent(jLabel15)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(84, 84, 84)
                                .addComponent(jLabel19))
                            .addComponent(jTextField4Fname1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(92, 92, 92)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField4Fonenumber1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jTextField4passold1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(updateProfileBtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(399, 399, 399))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField4Fname1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField4Fonenumber1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField4Username1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19UsernameError1)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField4passold1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPasswordField1passwordnew1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(updateProfileBtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(697, 697, 697)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonUpdateProfile1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton9))
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout jPanelProfile1Layout = new javax.swing.GroupLayout(jPanelProfile1);
        jPanelProfile1.setLayout(jPanelProfile1Layout);
        jPanelProfile1Layout.setHorizontalGroup(
            jPanelProfile1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProfile1Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(jPanelProfile1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addContainerGap(458, Short.MAX_VALUE))
        );
        jPanelProfile1Layout.setVerticalGroup(
            jPanelProfile1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProfile1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelProfileLayout = new javax.swing.GroupLayout(jPanelProfile);
        jPanelProfile.setLayout(jPanelProfileLayout);
        jPanelProfileLayout.setHorizontalGroup(
            jPanelProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProfileLayout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(493, Short.MAX_VALUE))
        );
        jPanelProfileLayout.setVerticalGroup(
            jPanelProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelProfileLayout.createSequentialGroup()
                .addContainerGap(126, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        tabsCategory.addTab("Profile", jPanelProfile);

        jPanel2.setBackground(new java.awt.Color(0, 51, 51));

        jLabel32.setBackground(new java.awt.Color(255, 255, 255));
        jLabel32.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("          Personal expenses monitoring System");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 808, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(269, 269, 269))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel32)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tabsCategory))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabsCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 559, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
 

    private void tabsCategoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabsCategoryMouseClicked
    
        if (currentUser == null) {
        JOptionPane.showMessageDialog(this, "Session error: No user logged in", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }
    UsernameTxt.setText(currentUser.getUsername());
    FnameTxt.setText(currentUser.getFullname());
    phoneNumberTxt.setText(currentUser.getPhoneNumber());
    oldPasswordTxt.setText(currentUser.getPassword());
    }//GEN-LAST:event_tabsCategoryMouseClicked

    private void tabsCategoryStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tabsCategoryStateChanged

    }//GEN-LAST:event_tabsCategoryStateChanged

    private void updateProfileBtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateProfileBtn3ActionPerformed
         String fname = FnameTxt.getText().trim();
        String username = UsernameTxt.getText().trim();
        String oldPass = String.valueOf(oldPasswordTxt.getPassword()).trim();
        String newPass = String.valueOf(newPasswordTxt.getPassword()).trim();
        String phone = phoneNumberTxt.getText().trim();
         if (fname.isEmpty() || username.isEmpty() || phone.isEmpty()) {
            jLabel19UsernameError.setText("Please fill all required fields");
            return;
        }

        if (!oldPass.equals(currentUser.getPassword())) {
            jLabel19UsernameError.setText("Incorrect old password");
            return;
        }

        try {
            User user = new User();
            user.setUsername(username);
            user.setPassword(newPass.isEmpty() ? oldPass : newPass);
            user.setFullname(fname);
            user.setPhoneNumber(phone);
            String feedback = userService.updateUser(user);
            if (feedback.toLowerCase().contains("success")) {
                currentUser.setUsername(username);
                currentUser.setPassword(newPass.isEmpty() ? oldPass : newPass);
                currentUser.setFullname(fname);
                currentUser.setPhoneNumber(phone);
                JOptionPane.showMessageDialog(this, "Profile updated successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, feedback, "Update Failed", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error updating profile: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
      
        
    }//GEN-LAST:event_updateProfileBtn3ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
//  no used 
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButtonUpdateProfile1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateProfile1ActionPerformed
  // not used
    }//GEN-LAST:event_jButtonUpdateProfile1ActionPerformed

    private void updateProfileBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateProfileBtnActionPerformed
         String fname = FnameTxt.getText().trim();
        String username = UsernameTxt.getText().trim();
        String oldPass = String.valueOf(oldPasswordTxt.getPassword()).trim();
        String newPass = String.valueOf(newPasswordTxt.getPassword()).trim();
        String phone = phoneNumberTxt.getText().trim();
         if (fname.isEmpty() || username.isEmpty() || phone.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please fill all required fields", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (!oldPass.equals(currentUser.getPassword())) {
            JOptionPane.showMessageDialog(this, "Incorrect old password", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            User user = new User();
            user.setUsername(username);
            user.setPassword(newPass.isEmpty() ? oldPass : newPass);
            user.setFullname(fname);
            user.setPhoneNumber(phone);
            String feedback = userService.updateUser(user);
            if (feedback != null && feedback.toLowerCase().contains("success")) {
                currentUser.setUsername(username);
                currentUser.setPassword(newPass.isEmpty() ? oldPass : newPass);
                currentUser.setFullname(fname);
                currentUser.setPhoneNumber(phone);
                JOptionPane.showMessageDialog(this, "Profile updated successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, feedback != null ? feedback : "Update Failed", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error updating profile: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_updateProfileBtnActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();       // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButtonUpdateProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateProfileActionPerformed
// not used 
    }//GEN-LAST:event_jButtonUpdateProfileActionPerformed

    private void jScrollPane2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane2MouseClicked
        // these is the scroll for the  search  you will add some functionality if need  also 
    }//GEN-LAST:event_jScrollPane2MouseClicked

    private void DisplayExpenseBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisplayExpenseBtn2ActionPerformed

      
          Date selectedDate = jDateChooserExpenseDate2.getDate();
        if (selectedDate == null) {
            JOptionPane.showMessageDialog(this, "Please select a date first!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        Calendar cal = Calendar.getInstance();
        cal.setTime(selectedDate);
        int selectedMonth = cal.get(Calendar.MONTH) + 1;
        int year = cal.get(Calendar.YEAR);

        try {
            Expense filter = new Expense();
            filter.setUser(currentUser);
            List<Expense> expenses = expenseService.retrieveAll(filter);
            DefaultTableModel model = new DefaultTableModel(new Object[]{"Amount", "Category", "Date", "Description"}, 0);
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");

            for (Expense e : expenses) {
                if (!isAdmin && !e.getUser().getUsername().equals(currentUser.getUsername())) continue;
                Calendar ec = Calendar.getInstance();
                ec.setTime(e.getDate());
                if (ec.get(Calendar.MONTH) + 1 == selectedMonth && ec.get(Calendar.YEAR) == year) {
                    model.addRow(new Object[]{
                        String.format("%.2f", e.getAmount()),
                        e.getCategory(),
                        sdf.format(e.getDate()),
                        e.getDescription()
                    });
                }
            }
            jTableExpense1.setModel(model);
            JOptionPane.showMessageDialog(this, "Results loaded successfully!", "Search Complete", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception ex) {
            expenseAddErrorLabel1.setText("Error searching: " + ex.getMessage());
            Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_DisplayExpenseBtn2ActionPerformed

    private void jPanelExpensesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelExpensesMouseClicked
    // these is not used 
     
    }//GEN-LAST:event_jPanelExpensesMouseClicked

    private void jScrollPane1ExpenseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane1ExpenseMouseClicked
       // these is the scroll for tables of record expense    you will functionality 
    }//GEN-LAST:event_jScrollPane1ExpenseMouseClicked

    private void jTableExpenseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableExpenseMouseClicked
        int Myindex = jTableExpense.getSelectedRow();
        if (Myindex != -1) { // Check if a valid row is selected
            ExpenseAmountTxt.setText(jTableExpense.getValueAt(Myindex, 0).toString());

            String comboItem = jTableExpense.getValueAt(Myindex, 1).toString();
            jComboBox2.setSelectedItem(comboItem);
            
            // CRITICAL: Retrieve and store the ID for Update/Delete
            // Assuming we need to fetch the ID from the service or it's hidden in the table
            // For now, let's try to get it if it's in the model or fetch all to match
            try {
                Expense filter = new Expense();
                filter.setUser(currentUser);
                List<Expense> expenses = expenseService.retrieveAll(filter);
                if (Myindex < expenses.size()) {
                    selectedExpenseId = expenses.get(Myindex).getId();
                }
            } catch (Exception ex) {
                Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, "Error retrieving ID", ex);
            }

            // For a JDateChooser you should parse string to date.
            try {
                String dateStr = jTableExpense.getValueAt(Myindex, 2).toString();
                DateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");
                Date date = formatter.parse(dateStr);
                jDateChooserExpenseDate1.setDate(date);
            } catch (ParseException e) {
                e.printStackTrace();
            }

            ExpenseDescriptionTxt.setText(jTableExpense.getValueAt(Myindex, 3).toString());
        } else {
            System.out.println("Please select a row to retrieve values from.");

        }// TODO add your handling code here:
        // TODO add your handling code here:
    }//GEN-LAST:event_jTableExpenseMouseClicked

    private void updateExpenseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateExpenseBtnActionPerformed
      
      
         if (selectedExpenseId == null) {
            expenseAddErrorLabel.setText("Select an expense to update");
            return;
        }

        String desc = ExpenseDescriptionTxt.getText().trim();
        String category = (String) jComboBox2.getSelectedItem();
        Date date = jDateChooserExpenseDate1.getDate();
        double amount;

        if (desc.isEmpty() || category == null || date == null) {
            expenseAddErrorLabel.setText("Please fill all fields");
            return;
        }

        try {
            amount = Double.parseDouble(ExpenseAmountTxt.getText().trim());
            if (amount <= 0) {
                expenseAddErrorLabel.setText("Amount must be positive");
                return;
            }
        } catch (NumberFormatException e) {
            expenseAddErrorLabel.setText("Invalid amount");
            return;
        }

        try {
            Expense expense = new Expense();
            expense.setId(selectedExpenseId);
            expense.setDescription(desc);
            expense.setAmount(amount);
            expense.setDate(date);
            expense.setCategory(category);
            expense.setUser(currentUser);
            String feedback = expenseService.updateExpense(expense);
            if (feedback == null) feedback = "Failed: Unknown server error";
            if (feedback.toLowerCase().contains("success")) {
                JOptionPane.showMessageDialog(this, "Expense updated successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
                Display();
                clearExpenseForm();
            } else {
                JOptionPane.showMessageDialog(this, feedback, "Update Failed", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception ex) {
            expenseAddErrorLabel.setText("Error updating expense: " + ex.getMessage());
            Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
    

    }//GEN-LAST:event_updateExpenseBtnActionPerformed

    private void SavePdfBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SavePdfBtnActionPerformed
        try {
            Expense filter = new Expense();
            filter.setUser(currentUser);
            List<Expense> expenses = expenseService.retrieveAll(filter);
            Document doc = new Document();
            PdfWriter.getInstance(doc, new FileOutputStream("Expenses_" + currentUser.getUsername() + ".pdf"));
            doc.open();
            doc.add(new Paragraph("Expenses Report for " + currentUser.getFullname()));
            doc.add(new Paragraph("Date: " + new SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(new Date())));
            doc.add(new Paragraph("\n"));
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            for (Expense e : expenses) {
                if (isAdmin || e.getUser().getUsername().equals(currentUser.getUsername())) {
                    doc.add(new Paragraph("Description: " + e.getDescription()));
                    doc.add(new Paragraph("Amount: " + String.format("%.2f", e.getAmount())));
                    doc.add(new Paragraph("Date: " + sdf.format(e.getDate())));
                    doc.add(new Paragraph("Category: " + e.getCategory()));
                    doc.add(new Paragraph(""));
                }
            }
            doc.close();
            JOptionPane.showMessageDialog(this, "PDF report generated successfully", "Success", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception ex) {
            expenseAddErrorLabel.setText("Error generating PDF: " + ex.getMessage());
            Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_SavePdfBtnActionPerformed

    private void DisplayExpenseBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisplayExpenseBtn1ActionPerformed
     

           Date selectedDate = jDateChooserExpenseDate2.getDate();
        if (selectedDate == null) {
            JOptionPane.showMessageDialog(this, "Please select a date first!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        Calendar cal = Calendar.getInstance();
        cal.setTime(selectedDate);
        int selectedMonth = cal.get(Calendar.MONTH) + 1;
        int year = cal.get(Calendar.YEAR);

        try {
            Expense filter = new Expense();
            filter.setUser(currentUser);
            List<Expense> expenses = expenseService.retrieveAll(filter);
            DefaultTableModel model = new DefaultTableModel(new Object[]{"Amount", "Category", "Date", "Description"}, 0);
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");

            for (Expense e : expenses) {
                if (!isAdmin && !e.getUser().getUsername().equals(currentUser.getUsername())) continue;
                Calendar ec = Calendar.getInstance();
                ec.setTime(e.getDate());
                if (ec.get(Calendar.MONTH) + 1 == selectedMonth && ec.get(Calendar.YEAR) == year) {
                    model.addRow(new Object[]{
                        String.format("%.2f", e.getAmount()),
                        e.getCategory(),
                        sdf.format(e.getDate()),
                        e.getDescription()
                    });
                }
            }
            jTableExpense1.setModel(model);
            JOptionPane.showMessageDialog(this, "Results loaded successfully!", "Search Complete", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception ex) {
            expenseAddErrorLabel1.setText("Error searching: " + ex.getMessage());
            Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
    

 
        // TODO add your handling code here:
    }//GEN-LAST:event_DisplayExpenseBtn1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
     // not need for  difinition 
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void ExpenseDescriptionTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExpenseDescriptionTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ExpenseDescriptionTxtActionPerformed


    
    
    
    
    
    
    
    
    
    private void ExpenseAddBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExpenseAddBtnActionPerformed
if (ExpenseAmountTxt == null || ExpenseDescriptionTxt == null || jComboBox2 == null || jDateChooserExpenseDate1 == null) {
        expenseAddErrorLabel.setText("UI components not initialized");
        return;
    }
    if (expenseService == null) {
        expenseAddErrorLabel.setText("Service not initialized");
        return;
    }
    if (currentUser == null || currentUser.getUsername() == null) {
        expenseAddErrorLabel.setText("No user logged in or invalid username");
        Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, "currentUser or username is null");
        return;
    }
    if (currentUser.getUsername() == null) {
        expenseAddErrorLabel.setText("Invalid user ID");
        Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, 
            "currentUser.getId() is null or 0 for user: {0}", currentUser.getUsername());
        return;
    }

    String desc = ExpenseDescriptionTxt.getText().trim();
    String category = (String) jComboBox2.getSelectedItem();
    Date date = jDateChooserExpenseDate1.getDate();
    double amount;

    if (desc.isEmpty() || category == null || date == null) {
        expenseAddErrorLabel.setText("Please fill all fields");
        return;
    }

    try {
        amount = Double.parseDouble(ExpenseAmountTxt.getText().trim());
        if (amount <= 0) {
            expenseAddErrorLabel.setText("Amount must be positive");
            return;
        }
    } catch (NumberFormatException e) {
        expenseAddErrorLabel.setText("Invalid amount");
        return;
    }

    try {
        Expense expense = new Expense();
        expense.setDescription(desc);
        expense.setAmount(amount);
        expense.setDate(date);
        expense.setCategory(category);
        expense.setUser(currentUser);
        String feedback = expenseService.insertExpense(expense);
        if (feedback == null) feedback = "Failed: Unknown server error";
        if (feedback.toLowerCase().contains("success")) {
            JOptionPane.showMessageDialog(this, "Expense added successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
            Display();
            clearExpenseForm();
        } else {
            JOptionPane.showMessageDialog(this, feedback, "Add Failed", JOptionPane.ERROR_MESSAGE);
        }
    } catch (Exception ex) {
        expenseAddErrorLabel.setText("Error adding expense: " + ex.getMessage());
        Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, "RMI error", ex);
    }
    }//GEN-LAST:event_ExpenseAddBtnActionPerformed

    private void DeleteExpenseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteExpenseBtnActionPerformed
  if (selectedExpenseId == null) {
            expenseAddErrorLabel.setText("Select an expense to delete");
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(this, "Delete this expense?", "Confirm", JOptionPane.YES_NO_OPTION);
        if (confirm != JOptionPane.YES_OPTION) return;

        try {
            Expense expense = new Expense();
            expense.setId(selectedExpenseId);
            expense.setUser(currentUser);
            String feedback = expenseService.deleteExpense(expense);
            if (feedback == null) feedback = "Failed: Unknown server error";
            if (feedback.toLowerCase().contains("success")) {
                JOptionPane.showMessageDialog(this, "Expense deleted successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
                Display();
                clearExpenseForm();
            } else {
                JOptionPane.showMessageDialog(this, feedback, "Delete Failed", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception ex) {
            expenseAddErrorLabel.setText("Error deleting expense: " + ex.getMessage());
            Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    }//GEN-LAST:event_DeleteExpenseBtnActionPerformed
 


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (Exception ex) {
        Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
    }

    java.awt.EventQueue.invokeLater(() -> {
        try {
            Registry registry = LocateRegistry.getRegistry("127.0.0.1", 5000);
            UserInterface userService = (UserInterface) registry.lookup("users");
            User user = userService.retrieveByUsername("testuser"); // Replace with login logic
            if (user != null && user.getUsername() != null) {
                new Dashboard(user).setVisible(true);
            } else {
                JOptionPane.showMessageDialog(null, "User not found or invalid ID", "Error", JOptionPane.ERROR_MESSAGE);
                Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, "User retrieval failed for testuser");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error connecting to server: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, "RMI connection failed", ex);
        }
    });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DeleteExpenseBtn;
    private javax.swing.JButton DisplayExpenseBtn1;
    private javax.swing.JButton DisplayExpenseBtn2;
    private javax.swing.JButton ExitBtn;
    private javax.swing.JButton ExpenseAddBtn;
    private javax.swing.JTextField ExpenseAmountTxt;
    private javax.swing.JTextField ExpenseDescriptionTxt;
    private javax.swing.JTextField FnameTxt;
    private javax.swing.JButton SavePdfBtn;
    private javax.swing.JTextField UsernameTxt;
    private javax.swing.JTextField avg;
    private javax.swing.JLabel expenseAddErrorLabel;
    private javax.swing.JLabel expenseAddErrorLabel1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton9;
    private javax.swing.JButton jButtonUpdateProfile;
    private javax.swing.JButton jButtonUpdateProfile1;
    private javax.swing.JComboBox<String> jComboBox2;
    private com.toedter.calendar.JDateChooser jDateChooserExpenseDate1;
    private com.toedter.calendar.JDateChooser jDateChooserExpenseDate2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel19UsernameError;
    private javax.swing.JLabel jLabel19UsernameError1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanelExpenses;
    private javax.swing.JPanel jPanelProfile;
    private javax.swing.JPanel jPanelProfile1;
    private javax.swing.JPasswordField jPasswordField1passwordnew1;
    private javax.swing.JScrollPane jScrollPane1Expense;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableExpense;
    private javax.swing.JTable jTableExpense1;
    private javax.swing.JTextField jTextField4Fname1;
    private javax.swing.JTextField jTextField4Fonenumber1;
    private javax.swing.JTextField jTextField4Username1;
    private javax.swing.JPasswordField jTextField4passold1;
    private javax.swing.JPasswordField newPasswordTxt;
    private javax.swing.JPasswordField oldPasswordTxt;
    private javax.swing.JTextField phoneNumberTxt;
    private javax.swing.JButton searchExpenses;
    private javax.swing.JTabbedPane tabsCategory;
    private javax.swing.JTextField total;
    private javax.swing.JButton updateExpenseBtn;
    private javax.swing.JButton updateProfileBtn;
    private javax.swing.JButton updateProfileBtn3;
    // End of variables declaration//GEN-END:variables

private void Display() {
    if (expenseService == null || currentUser == null || currentUser.getUsername() == null) {
        expenseAddErrorLabel.setText("Service or user not initialized");
        return;
    }
    if (currentUser.getUsername() == null ) {
        expenseAddErrorLabel.setText("Invalid user ID");
        Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, 
            "currentUser.getId() is null or 0 for user: {0}", currentUser.getUsername());
        return;
    }
    DefaultTableModel model = (DefaultTableModel) jTableExpense.getModel();
    model.setRowCount(0);
    double sum = 0;
    int count = 0;

    try {
        Expense filter = new Expense();
        filter.setUser(currentUser);
        List<Expense> expenses = expenseService.retrieveAll(filter);
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");

        for (Expense expense : expenses) {
            if (isAdmin || (expense.getUser() != null && expense.getUser().getUsername().equals(currentUser.getUsername()))) {
                model.addRow(new Object[]{
                    String.format("%.2f", expense.getAmount()),
                    expense.getCategory(),
                    dateFormat.format(expense.getDate()),
                    expense.getDescription()
                });
                sum += expense.getAmount();
                count++;
            }
        }

        total.setText(String.format("%.2f", sum));
        avg.setText(String.format("%.2f", count > 0 ? sum / count : 0.0));
    } catch (Exception ex) {
        expenseAddErrorLabel.setText("Error fetching expenses: " + ex.getMessage());
        Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, "RMI error", ex);
    }
}



     private void clearExpenseForm() {
        ExpenseAmountTxt.setText("");
        ExpenseDescriptionTxt.setText("");
        jComboBox2.setSelectedIndex(-1);
        jDateChooserExpenseDate1.setDate(null);
        selectedExpenseId = null;
        expenseAddErrorLabel.setText("");
    }
}
