version: '3.8'

services:
  db:
    image: postgres:15
    container_name: pems-db
    environment:
      POSTGRES_DB: personnel_expense_monitoring_system_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: impano12@
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  server:
    build: .
    container_name: pems-server
    ports:
      - "5000:5000"
    environment:
      - DB_URL=jdbc:postgresql://db:5432/personnel_expense_monitoring_system_db
    depends_on:
      - db

volumes:
  postgres_data:
